<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>Scp096Mask</AssemblyName>
    <RootNamespace>Scp096Mask</RootNamespace>
    <OutputType>Library</OutputType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(EXILED_REFERENCES)/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(EXILED_REFERENCES)/Assembly-CSharp-firstpass.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>$(EXILED_REFERENCES)/Mirror.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(EXILED_REFERENCES)/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(EXILED_REFERENCES)/UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(EXILED_REFERENCES)/UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(EXILED_REFERENCES)/UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Exiled.API">
      <HintPath>$(EXILED_REFERENCES)/Exiled.API.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Exiled.Events">
      <HintPath>$(EXILED_REFERENCES)/Exiled.Events.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Exiled.Loader">
      <HintPath>$(EXILED_REFERENCES)/Exiled.Loader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="HarmonyLib">
      <HintPath>$(EXILED_REFERENCES)/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MEC">
      <HintPath>$(EXILED_REFERENCES)/MEC.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UserSettings">
      <HintPath>$(EXILED_REFERENCES)/UserSettings.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="HintServiceMeow.Core">
      <HintPath>$(EXILED_REFERENCES)/HintServiceMeow.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="CommandSystem.Core">
      <HintPath>$(EXILED_REFERENCES)/CommandSystem.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="**/*.cs" />
  </ItemGroup>
</Project>