<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>SCPRoleplayPlugin</AssemblyName>
    <RootNamespace>SCPRoleplayPlugin</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>Dependencies\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>Dependencies\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.API">
      <HintPath>Dependencies\Exiled.API.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.Events">
      <HintPath>Dependencies\Exiled.Events.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.Permissions">
      <HintPath>Dependencies\Exiled.Permissions.dll</HintPath>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>Dependencies\Mirror.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>Dependencies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>Dependencies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>