<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>SCP035</AssemblyName>
    <RootNamespace>SCP035</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Exiled.API">
      <HintPath>../../../lib/Exiled.API.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Exiled.Events">
      <HintPath>../../../lib/Exiled.Events.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Exiled.Loader">
      <HintPath>../../../lib/Exiled.Loader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>../../../lib/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>../../../lib/Mirror.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="NorthwoodLib">
      <HintPath>../../../lib/NorthwoodLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PluginAPI">
      <HintPath>../../../lib/PluginAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>