<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>WelcomeBroadcast</AssemblyName>
    <RootNamespace>WelcomeBroadcast</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <NoWarn>NU1605</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Exiled.API">
      <HintPath>$(EXILED_LIBS)/Exiled.API.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Exiled.Events">
      <HintPath>$(EXILED_LIBS)/Exiled.Events.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Exiled.Loader">
      <HintPath>$(EXILED_LIBS)/Exiled.Loader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Exiled.CreditTags">
      <HintPath>$(EXILED_LIBS)/Exiled.CreditTags.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(EXILED_LIBS)/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>$(EXILED_LIBS)/Mirror.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="NorthwoodLib">
      <HintPath>$(EXILED_LIBS)/NorthwoodLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(EXILED_LIBS)/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(EXILED_LIBS)/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="$(EXILED_LIBS)/**" Visible="false" />
  </ItemGroup>
</Project>